/**
 * @fileoverview `all` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import base from './base.js';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @type {Linter.Config} */
export default {
  ...base,
  name: 'mark/all',
  rules: {
    'mark/allow-heading': 'error',
    'mark/alt-text': 'error',
    'mark/code-lang-shorthand': 'error',
    'mark/consistent-delete-style': 'error',
    'mark/consistent-emphasis-style': 'error',
    'mark/consistent-strong-style': 'error',
    'mark/consistent-thematic-break-style': 'error',
    'mark/en-capitalization': 'error',
    'mark/heading-id': 'error',
    'mark/image-title': 'error',
    'mark/no-bold-paragraph': 'error',
    'mark/no-control-character': 'error',
    'mark/no-curly-quote': 'error',
    'mark/no-double-space': 'error',
    'mark/no-emoji': 'error',
    'mark/no-git-conflict-marker': 'error',
    'mark/no-irregular-dash': 'error',
    'mark/no-irregular-whitespace': 'error',
    'mark/no-unused-definition': 'error',
  },
};
