/**
 * @fileoverview `recommended` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import base from './base.js';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @type {Linter.Config} */
export default {
  ...base,
  name: 'mark/recommended',
  rules: {
    'mark/alt-text': 'error',
    'mark/no-bold-paragraph': 'error',
    'mark/no-control-character': 'error',
    'mark/no-double-space': 'error',
    'mark/no-git-conflict-marker': 'error',
    'mark/no-irregular-whitespace': 'error',
    'mark/no-unused-definition': 'error',
  },
};
