/**
 * @fileoverview `recommended` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import base from './base.js';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @satisfies {Linter.Config} */
export default /** @type {const} */ ({
  ...base,
  name: 'mark/recommended',
  plugins: {
    ...base.plugins,
  },
  rules: {
    'markdown/no-unused-definitions': 'error',
    'mark/alt-text': 'error',
    'mark/code-lang-shorthand': 'error',
    'mark/no-bold-paragraph': 'error',
    'mark/no-control-character': 'error',
    'mark/no-curly-quote': 'error',
    'mark/no-double-space': 'error',
    'mark/no-git-conflict-marker': 'error',
    'mark/no-irregular-dash': 'error',
    'mark/no-irregular-whitespace': 'error',
  },
});
