/**
 * @fileoverview `stylistic` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @satisfies {Linter.Config} */
export default /** @type {const} */ ({
  name: 'mark/stylistic',
  files: ['**/*.md'],
  plugins: {
    markdown,
  },
  languageOptions: {
    frontmatter: 'yaml',
  },
  language: 'markdown/gfm',
  rules: {
    'mark/consistent-delete-style': 'error',
    'mark/consistent-emphasis-style': 'error',
    'mark/consistent-strong-style': 'error',
    'mark/consistent-thematic-break-style': 'error',
  },
});
