/**
 * @fileoverview Stylistic configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import base from './base.js';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @type {Linter.Config} */
export default {
  ...base,
  name: 'mark/stylistic',
  rules: {
    'mark/consistent-delete-style': 'error',
    'mark/consistent-emphasis-style': 'error',
    'mark/consistent-strong-style': 'error',
    'mark/consistent-thematic-break-style': 'error',
  },
};
