/**
 * @fileoverview `all` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { ESLint, Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @param {ESLint.Plugin} plugin */
export default function all(plugin) {
  /** @satisfies {Linter.Config} */
  return /** @type {const} */ ({
    name: 'md/all',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get md() {
        return plugin;
      },
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
    rules: {
      'markdown/no-unused-definitions': 'error',
      'md/allow-heading': 'error',
      'md/allow-image-url': 'error',
      'md/allow-link-url': 'error',
      'md/code-lang-shorthand': 'error',
      'md/consistent-delete-style': 'error',
      'md/consistent-emphasis-style': 'error',
      'md/consistent-strong-style': 'error',
      'md/consistent-thematic-break-style': 'error',
      'md/en-capitalization': 'error',
      'md/heading-id': 'error',
      'md/no-bold-paragraph': 'error',
      'md/no-control-character': 'error',
      'md/no-curly-quote': 'error',
      'md/no-double-space': 'error',
      'md/no-emoji': 'error',
      'md/no-git-conflict-marker': 'error',
      'md/no-irregular-dash': 'error',
      'md/no-irregular-whitespace': 'error',
      'md/no-url-trailing-slash': 'error',
      'md/require-image-title': 'error',
      'md/require-link-title': 'error',
    },
  });
}
