/**
 * @fileoverview `all` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.js`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';
import type { ESLint, Linter } from 'eslint';

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

export default function all(plugin: ESLint.Plugin) {
  return {
    name: 'md/all',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get md() {
        return plugin;
      },
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
    rules: {
      'md/allow-heading': 'error',
      'md/allow-image-url': 'error',
      'md/allow-link-url': 'error',
      'md/code-lang-shorthand': 'error',
      'md/consistent-code-style': 'error',
      'md/consistent-delete-style': 'error',
      'md/consistent-emphasis-style': 'error',
      'md/consistent-inline-code-style': 'error',
      'md/consistent-strong-style': 'error',
      'md/consistent-thematic-break-style': 'error',
      'md/consistent-unordered-list-style': 'error',
      'md/no-consecutive-blank-line': 'error',
      'md/no-control-character': 'error',
      'md/no-curly-quote': 'error',
      'md/no-double-punctuation': 'error',
      'md/no-double-space': 'error',
      'md/no-emoji': 'error',
      'md/no-git-conflict-marker': 'error',
      'md/no-irregular-dash': 'error',
      'md/no-irregular-whitespace': 'error',
      'md/no-tab': 'error',
      'md/no-trailing-heading-punctuation': 'error',
      'md/no-url-trailing-slash': 'error',
      'md/require-heading-id': 'error',
      'md/require-image-title': 'error',
      'md/require-link-title': 'error',
    },
  } as const satisfies Linter.Config;
}
