/**
 * @fileoverview `base` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { ESLint, Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @param {ESLint.Plugin} plugin */
export default function base(plugin) {
  /** @satisfies {Linter.Config} */
  return /** @type {const} */ ({
    name: 'md/base',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get md() {
        return plugin;
      },
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
  });
}
