/**
 * @fileoverview `base` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.js`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';
import type { ESLint, Linter } from 'eslint';

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

export default function base(plugin: ESLint.Plugin) {
  return {
    name: 'md/base',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get md() {
        return plugin;
      },
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
  } as const satisfies Linter.Config;
}
