/**
 * @fileoverview `recommended` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { ESLint, Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @param {ESLint.Plugin} plugin */
export default function recommended(plugin) {
  /** @satisfies {Linter.Config} */
  return /** @type {const} */ ({
    name: 'mark/recommended',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get mark() {
        return plugin;
      },
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
    rules: {
      'markdown/no-unused-definitions': 'error',
      'mark/alt-text': 'error',
      'mark/code-lang-shorthand': 'error',
      'mark/no-bold-paragraph': 'error',
      'mark/no-control-character': 'error',
      'mark/no-curly-quote': 'error',
      'mark/no-double-space': 'error',
      'mark/no-git-conflict-marker': 'error',
      'mark/no-irregular-dash': 'error',
      'mark/no-irregular-whitespace': 'error',
    },
  });
}
