/**
 * @fileoverview `stylistic` configuration.
 * WARNING: This file is autogenerated using the `scripts/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { ESLint, Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @param {ESLint.Plugin} plugin */
export default function stylistic(plugin) {
  /** @satisfies {Linter.Config} */
  return /** @type {const} */ ({
    name: 'md/stylistic',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get md() {
        return plugin;
      },
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
    rules: {
      'md/consistent-delete-style': 'error',
      'md/consistent-emphasis-style': 'error',
      'md/consistent-strong-style': 'error',
      'md/consistent-thematic-break-style': 'error',
      'md/no-tab': 'error',
    },
  });
}
