/**
 * @fileoverview Script to build configs for `eslint-markdown`.
 * Usage: `node path/to/build-config.mjs`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import { writeFileSync } from 'node:fs';
import markdown from 'eslint-markdown';
import prettier from 'prettier'; // eslint-disable-line import/no-extraneous-dependencies -- Required

// --------------------------------------------------------------------------------
// Helper
// --------------------------------------------------------------------------------

/**
 * @param {'all' | 'base' | 'recommended' | 'stylistic'} configName
 * @param {Record<string, string>} rules
 */
async function generateCode(configName, rules) {
  const url = new URL(
    `../packages/eslint-markdown/src/configs/${configName}.js`,
    import.meta.url,
  );
  const prettierConfig = await prettier.resolveConfig(url);
  const code = `
/**
 * @fileoverview \`${configName}\` configuration.
 * WARNING: This file is autogenerated using the \`scripts/build-config.mjs\`
 */

// --------------------------------------------------------------------------------
// Import
// --------------------------------------------------------------------------------

import markdown from '@eslint/markdown';

// --------------------------------------------------------------------------------
// Typedef
// --------------------------------------------------------------------------------

/**
 * @import { ESLint, Linter } from "eslint";
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @param {ESLint.Plugin} plugin */
export default function ${configName}(plugin) {
  /** @satisfies {Linter.Config} */
  return /** @type {const} */ ({
    name: 'md/${configName}',
    files: ['**/*.md'],
    plugins: {
      markdown,
      get md() {
        return plugin;
      }
    },
    languageOptions: {
      frontmatter: 'yaml',
    },
    language: 'markdown/gfm',
    ${configName === 'base' ? '' : `rules: ${JSON.stringify(rules)},`}
  });
}
`.trimStart();

  writeFileSync(
    url,
    await prettier.format(code, { filepath: url.pathname, ...prettierConfig }),
  );
}

// --------------------------------------------------------------------------------
// Script
// --------------------------------------------------------------------------------

const allRules = {
  'markdown/no-unused-definitions': 'error', // TODO: Remove this line once integrated with `@eslint/markdown`.
};
const baseRules = {};
const recommendedRules = {
  'markdown/no-unused-definitions': 'error', // TODO: Remove this line once integrated with `@eslint/markdown`.
};
const stylisticRules = {};

for (const [ruleName, rule] of Object.entries(markdown.rules)) {
  allRules[`md/${ruleName}`] = 'error';

  if (rule.meta.docs.recommended === true) {
    recommendedRules[`md/${ruleName}`] = 'error';
  }

  if (rule.meta.docs.stylistic === true) {
    stylisticRules[`md/${ruleName}`] = 'error';
  }
}

generateCode('all', allRules);
generateCode('base', baseRules);
generateCode('recommended', recommendedRules);
generateCode('stylistic', stylisticRules);
